apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          # Replace 693925625409 and <region> accordingly
          image: 693925625409.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
          ports:
            - containerPort: 80
          env:
            # Replace the following environment values with your actual DB credentials
            - name: DB_HOST
              value: mini-db.cluster-c8144088qwb4.us-east-1.rds.amazonaws.com        # Replace accordingly
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres                          # Replace accordingly
            - name: DB_USER
              value: postgres                      # Replace accordingly
            - name: DB_PASSWORD
              value: Rockyandquiely3944                      # Replace accordingly

